version: '3.7'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: booking_app_local
    env_file:
      - .env.production
    environment:
      RUN_MIGRATION: 1
      NODE_ENV: production
    ports:
      - '3333:${PORT}'
    networks:
      - booking_app_network

networks:
  booking_app_network:
    name: booking_app_network
    driver: bridge
